#/bin/bash
INPUT_FILE="./HS22.fasta.indexed"
N_THREADS="1"
WRITE_MAWS="1"
OUTPUT_FILE="./HS22.fasta.maws.filter"

# Statistics
MIN_HISTOGRAM_LENGTH="2"
MAX_HISTOGRAM_LENGTH="1000"
COMPUTE_SCORES="1"

# Filtering by length
MIN_LENGTH="2"
MAX_LENGTH="100000"

# Filtering by score
SELECT_SCORE="3"
SCORE_THRESHOLD="2"

# Compression
COMPRESS_OUTPUT="0"


./run_MAWs_single ${INPUT_FILE} ${N_THREADS} \
	${MIN_LENGTH} ${MAX_LENGTH} \
	${MIN_HISTOGRAM_LENGTH} ${MAX_HISTOGRAM_LENGTH} \
	${COMPUTE_SCORES} ${SELECT_SCORE} ${SCORE_THRESHOLD} \
	${WRITE_MAWS} ${OUTPUT_FILE} ${COMPRESS_OUTPUT}